packages:
  - apps/*
  - libs/**
  - packages/*
catalog:
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-slot": ^1.2.4
  "@tailwindcss/postcss": ^4.1.18
  "@tailwindcss/vite": ^4.1.18
  "@types/node": ^22.0.0
  "@types/react": ^19.2.8
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.562.0
  next: ^16.0.7
  next-themes: ^0.4.6
  react: ^19.2.3
  react-dom: ^19.2.3
  react-router-dom: ^7.12.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.0.3
  vitest: ^3.2.4
